test secret key deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -9,18 +9,7 @@ jobs:
   ssh-test:
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout repository
-        uses: actions/checkout@v2
+      - name: Check if SSH key exists
+      run: |
+        echo "${{ secrets.SSH_PRIVATE_KEY }}" || echo "SSH_PRIVATE_KEY is missing!"
 
-      - name: Debugging SSH Setup
-        run: |
-          mkdir -p ~/.ssh
-          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
-          chmod 600 ~/.ssh/id_rsa
-          ssh-keyscan 87.248.150.99 >> ~/.ssh/known_hosts
-          ls -la ~/.ssh
-          cat ~/.ssh/id_rsa || echo "Failed to read id_rsa"
-
-      - name: Test SSH connection
-        run: |
-          ssh -o StrictHostKeyChecking=no -T app@87.248.150.99 "echo 'SSH connection successful!'"
