Update node.js.yml

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -14,10 +14,20 @@ jobs:
     - name: Checkout Code
       uses: actions/checkout@v3
       
-    # 2. تأیید نسخه‌های نصب شده
-    - name: connect server
+    # Step 1: Setup SSH
+    - name: Setup SSH
       run: |
-        ssh -p 9011 -o StrictHostKeyChecking=no app@87.248.150.99
+        mkdir -p ~/.ssh
+        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
+        chmod 600 ~/.ssh/id_rsa
+        ssh-keyscan -p 9011 -H 87.248.150.99 >> ~/.ssh/known_hosts
+        ls -la ~/.ssh
+        cat ~/.ssh/id_rsa || echo "Failed to read private key"
+
+    # Step 2: Test SSH connection
+    - name: Test SSH connection
+      run: |
+        ssh -p 9011 -o StrictHostKeyChecking=no app@87.248.150.99 "echo 'SSH connection successful!'"
         
     # 3. تأیید نسخه‌های نصب شده
     - name: Verify Node.js and npm versions
